title: Oussama Bechar # your name (or website title) here
logo: "images/Imgportfolio.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey Everyone, this is my Portfolio.
  I am a Renewable Energy Engineer with a lot of passion for Data.
  My Transferable skills from my Education and previous roles , plus my technical knowledge in Excel, SQL and
  Tableau are a big tool that I use to solve complex problems,  and provide valuable insights that drive informed business decisions.<br><br>
  <a href="https://www.linkedin.com/in/oussamabechar/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
