title: Oussama Bechar # your name (or website title) here
logo: "images/OUSS.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey Everyone, Welcome to my portfolio. I am a Data enthusiast with a solid foundation in Physics & Mathematics, which I leverage to uncover meaningful insights within complex data.
  I am dedicated to continuous learning, staying at the forefront of cutting-edge data analysis techniques and tools. My goal is to make a positive impact by harnessing the power of data to solve real-world challenges and drive innovation.<br><br>
  <a href="https://www.linkedin.com/in/oussamabechar/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
