title: Oussama Bechar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
<br><br>
<br><br>
  Hey Everyone, this is my Portfolio.
  I am a renewable energy engineer with a lot of passion to Data.
  My Transferable skills from my Education and previous roles , plus my technical knowledge in Excel, SQL and
  Tableau are a big tool that I use to solve complex problems, and transform raw data
  into meangniful insights, and make data-driven decisions.<br><br>
  <a href="https://www.linkedin.com/in/oussamabechar/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
